server:
    interface: 127.0.0.1
    port: 53
    access-control: 127.0.0.0/8 allow
    do-ip6: no
    prefer-ip6: no
    hide-identity: yes
    hide-version: yes
    num-threads: 2
    msg-cache-size: 32m
    rrset-cache-size: 64m
    prefetch: yes
forward-zone:
    name: "ts.net."
    forward-addr: 100.100.100.100
forward-zone:
    name: "tail9e10b.ts.net."
    forward-addr: 100.100.100.100
forward-zone:
    name: "."
    forward-addr: 127.0.0.1@5354
    forward-addr: 1.1.1.1
    forward-addr: 9.9.9.9
