# Machine type
machine_type = "x86_64-linux"

# Paths
gpg_path = "/bin/gpg"
xauth_loc = "/bin/xauth"

################
# Conditionals #
################

is_remote = "true"
use_mamba = "true"

# Only one of the following
eval_zsh = "false"
eval_bash = "true"
