# Machine type
machine_type = "x86_64-linux"

# Paths
gpg_path = "/bin/gpg"
xauth_loc = "/bin/xauth"

################
# Conditionals #
################

is_remote = "true"
use_mamba = "true"
use_nvm = "true"
