# /etc/tmpfiles.d/buildbot.conf
d /var/lib/builds 0775 rgoswami rgoswami -
d /var/lib/builds/tmp 1777 rgoswami rgoswami 7d
d /var/cache/sccache 1777 root rgoswami -
d /var/lib/buildbot-nix 0755 rgoswami rgoswami -
d /var/lib/apptainer-cache 1777 rgoswami rgoswami -
