{
	'minimum_line_height' : 120.0,
	'insert_blank_line_size' : 0.5,
	'smarten_punctuation' : False,
	'embed_all_fonts' : False,
	'transform_css_rules' : '[]',
	'remove_paragraph_spacing_indent_size' : 1.5,
	'unsmarten_punctuation' : False,
	'disable_font_rescaling' : False,
	'extra_css' : None,
	'line_height' : 0.0,
	'expand_css' : False,
	'linearize_tables' : False,
	'filter_css' : u'',
	'base_font_size' : 0.0,
	'embed_font_family' : None,
	'remove_paragraph_spacing' : False,
	'subset_embedded_fonts' : False,
	'insert_blank_line' : False,
	'input_encoding' : None,
	'font_size_mapping' : None,
	'keep_ligatures' : False,
	'change_justification' : u'original',
	'asciiize' : False,
}