# Path to your dotfiles relative to your $HOME directory
dotfiles_dir = "Git/Github/Dotfiles/profiles"

##########
# Common #
##########
[settings]
# An array of toml files paths containing the variables to inject in your templatize dotfiles
# You can have multiple var files as long as variable names does not colide. 
vars = [ "common/vars.toml" ]
# An array of post install shell commands
hooks = ["bash -c \"chmod 600 ~/.ssh/config\""]
[settings.dots]
# A dot entry representing a symlink, `source` is relative to `dotfiles_dir` 
# and `target` shall be relative to $HOME directory or absolute.
 
# Git #
git_config = { source = "common/git/config", target = ".gitconfig" }
# Alacritty #
alacritty = { source = "common/.config/alacritty/alacritty.yml", target = ".config/alacritty/alacritty.yml" }
# Neovim #
vimrc = { source = "common/.vimrc", target = ".vimrc" }
neovim = { source = "common/.config/nvim/init.vim", target = ".config/nvim/init.vim" }
# Base Shell #
shellrc = { source = "common/shell/.shellrc", target = ".shellrc" }
# Zsh #
zshenv = { source = "common/shell/zsh/.zshenv", target = ".zshenv" }
zshrc = { source = "common/shell/zsh/.zshrc", target = ".zshrc" }
# Tmux #
tmuxconf =  { source = "common/shell/tmux/.tmux.conf", target = ".tmux.conf" }
# ssh #
sshconf =  { source = "common/ssh/config", target = ".ssh/config" }

#########
# MacOS #
#########
[profiles.macos]
vars = [ "macOS/mac-vars.toml" ]
hooks = [ "echo \"Welcome to the MacOS configuration\"", "skhd -r" ]
[profiles.macos.dots]
nix_darwin = { source = "macOS/nix-darwin/darwin-conf.nix", target=".nixpkgs/darwin-configuration.nix" }
yabairc = { source = "macOS/tilingWM/yabairc", target = ".config/yabai/yabairc" }
spacebarrc = { source = "macOS/tilingWM/spacebarrc", target = ".config/spacebar/spacebarrc" }
skhdrc = { source = "macOS/tilingWM/skhdrc", target = ".config/skhd/skhdrc" }

#########
# Linux #
#########
[profiles.linux]
vars = ["linux/linux-vars.toml"]
[profiles.linux.dots]
termiti = { source = "linux/.config/termite/alacritty.yml", target = ".config/alacritty/alacritty.yml" }

#######
# HPC #
#######
[profiles.hpc]
vars = ["hpc/hpc-vars.toml"]
[profiles.hpc.dots]
spack_modules = { source = "hpc/spack/modules.yml", target = ".spack/modules.yaml" }
