* Dots
These are ~dotfiles~ for various essential utilities mostly based around a tiling mouseless workflow. Prominently there are a lot of commandline configurations including ~zsh~, ~tmux~, ~neovim~ and others.

These have a long history; and older versions were managed by ~dotgit~ before that project transitioned to being re-written in ~python~.
** Usage
At the moment there are fewer install targets compared to the earlier set.
*** Tooling
We expect [[https://rustup.rs/][rustup]].
#+begin_code bash
rustup install stable
cargo install toml-bombadil
cd $DOTS # This is wherever the repo is
bombadil install -c bombadil.toml
#+end_code
Now we are ready to use any of the profiles present. Currently for the base:
#+begin_code bash
bombadil link
#+end_code
Other profiles can be selected in an equally intuitive manner.
#+begin_code bash
bombadil link -p macos
#+end_code
** Forking Guide
Some parts of the configuration *must* be changed. For a minimally invasive change just modify the ~vars~ files. In particular:
- Git :: This contains my settings, along with my signing key, so these will need to be changed
- SSH :: The keys very likely need to be changed
** Spinoffs and Changes
As of the 11th of April, 2019, the configuration for my `emacs` setup, with `doom-emacs` has been moved to [a repository of its own](https://github.com/HaoZeke/dotDoom).

As of the 7th of August, 2020, the HPC cluster [Lmod](https://lmod.readthedocs.io) configuration has been moved to [a repository of its own](https://github.com/HaoZeke/hzHPC_lmod).

Currently these are managed with [[https://github.com/oknozor/toml-bombadil][toml-bombadil]].
* License
This is still under the Unlicense.
