# GRE Word List
#
# Opt-in: the word list is cloned and generated by the run_once_get_gre_words
# chezmoi script, which only does anything when SETUP_GRE_WORDS=true. On a host
# that never set it there is nothing to print, and nothing to nag about either.
#
# The pick is done here rather than through the repo's random_gre.sh, which
# spends four processes on it -- wc to count the lines, shuf to choose one, and
# two sed passes to cut it out and strip the delimiters -- for 22 ms on every
# interactive shell. `shuf -n 1` reads the file and picks in one, and the
# delimiter strip and escape expansion are both builtins.
_gre_list=$HOME/.local/greWords/gre-cli-words/custom_gre_word_list
if [[ $- = *i* ]] && [ -r "$_gre_list" ]; then
    _gre_word=$(shuf -n 1 "$_gre_list")
    printf '%b\n' "${_gre_word//|/}"
fi
unset _gre_list _gre_word

# Emacs Stuff (cross platform)
# Local Variables:
# mode: shell-script
# End:
