# GRE Word List
#
# Opt-in: the word list is cloned and generated by the run_once_get_gre_words
# chezmoi script, which only does anything when SETUP_GRE_WORDS=true. On a host
# that never set it there is nothing to print, and nothing to nag about either.
if [[ $- = *i* ]] && [[ -d $HOME/.local/greWords/gre-cli-words ]]; then
    $HOME/.local/greWords/gre-cli-words/random_gre.sh $HOME/.local/greWords/gre-cli-words/custom_gre_word_list
fi

# Emacs Stuff (cross platform)
# Local Variables:
# mode: shell-script
# End:
