#! /bin/sh

bspc config border_width        2
bspc config window_gap        12

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer false
bspc config auto_alternate true
bspc config auto_cancel true
#bspc config normal_border_color "#79CDCD"
#bspc config active_border_color "#66CCCC"
#bspc config focused_border_color "#5F9F9F"
#bspc config presel_feedback_color "#528B8B"
#bspc config urgent_border_color "#8DEEEE"
#bspc config focused_locked_border_color "#008080"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

# Needed for mouse compatibility
bspc config click_to_focus true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action1 resize_corner

bspc monitor VGA-0 -d I II III IV V 
bspc monitor DVI-0 -d VI VII VIII IX X

# Padding
bspc config top_padding       16

bspc rule -a Gimp desktop=^8 follow=on state=floating
bspc rule -a Chromium desktop=^2
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Float
bspc rule -a mplayer2 state=floating
bspc rule -a smplayer state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a thunderbird state=floating
bspc rule -a Cantata state=floating
bspc rule -a Audacious state=floating
bspc rule -a Xfce4-taskmanager state=floating
bspc rule -a File-roller state=floating
bspc rule -a Nitrogen state=floating
# Special (Main.py is for guake)
bspc rule -a Main.py state=floating focus=on locked=on manage=on
bspc rule -a Tilda state=floating focus=on locked=on manage=on
bspc rule -a Synapse state=floating follow=on focus=on manage=on border=off
bspc rule -a Xfce4-notes state=floating follow=on focus=on

# AutoStart
compton --config ~/.config/compton.conf -b  
xfce4-volumed-pulse &
java_nonreparenting &
calibre-server --port 8264 --auto-reload --username haozeke --daemonize &
thunar --daemon &
synapse -s &
nm-applet &
#acd_cli mount /run/media/haozeke/Storage/Amazon/ &
#feh --bg-scale /run/media/haozeke/Storage/Pictures/Wallpapers/DeviantART/favorite\ star/1920x1200.jpg &
nitrogen --restore &
gnome-encfs-manager &
tilda &
tilda &
xsettingsd &
xfce4-panel --disable-wm-check &
#~/.config/bspwm/panel &
#stalonetray &
