# Defaults
terminal = "alacritty"
 
# Machine type
machine_type = "universal-darwin"

# Program paths
gpg_path = "/usr/local/bin/gpg" # brew
xauth_loc = "/opt/X11/bin/xauth" # XQuartz

################
# Conditionals #
################

is_remote = "true"
use_mamba = "true"
use_nvm = "true"
eval_zsh = "true"
eval_bash = "false"
