# -*- conf -*-
# From https://github.com/doomemacs/themes/blob/master/themes/doom-solarized-dark-high-contrast-theme.el
# Solarized dark high contrast

[cursor]
color= 002732 8d9fa1

[colors]
background= 002732
foreground= 8d9fa1
regular0=   01323d
regular1=   ec423a
regular2=   93a61a
regular3=   c49619
regular4=   3c98e0
regular5=   e2468f
regular6=   3cafa5
regular7=   eee8d5

# regularN brightened by increasing luminance by 20%
bright0=    08404f
bright1=    e35f5c
bright2=    9fb700
bright3=    d9a400
bright4=    4ba1de
bright5=    dc619d
bright6=    32c1b6
bright7=    ffffff

# Enable if prefer solarized colors instead of inverted fg/bg for
# highlighting (mouse selection)
# selection-foreground=93a1a1
# selection-background=073642
