# Kanged from https://github.com/doomemacs/themes/blob/master/themes/doom-acario-light-theme.el
[colors-dark]
foreground = 0F1019
background = F5F5F9

regular0 = 4E4E4E   # black
regular1 = D70000   # red
regular2 = 005F00   # green
regular3 = AF8700   # yellow
regular4 = 1F55A0   # blue
regular5 = AF005F   # magenta
regular6 = 007687   # cyan
regular7 = 0F1019   # white

bright0 = 303030    # bright black
bright1 = D70000    # bright red
bright2 = 005F00    # bright green
bright3 = AF8700    # bright yellow
bright4 = 1F55A0    # bright blue
bright5 = AF005F    # bright magenta
bright6 = 007687    # bright cyan
bright7 = 0F1019    # bright white

dim0 = 373e4d   # dim black
dim1 = 94545d   # dim red
dim2 = 809575   # dim green
dim3 = b29e75   # dim yellow
dim4 = 68809a   # dim blue
dim5 = 8c738c   # dim magenta
dim6 = 6d96a5   # dim cyan
dim7 = aeb3bb   # dim white

16 = AF005F  # extra color 1
17 = AF8700  # extra color 2
18 = E9E9F2  # base1
19 = D0D0E3  # base0
20 = 007687  # cyan
21 = 0F1019  # foreground

#selection-foreground=<inverse foreground/background>
#selection-background=<inverse foreground/background>
jump-labels=4E4E4E AF8700
urls=AF8700
