# -*- conf -*-
# Converted from the doom-tomorrow-night Emacs theme
# xref: https://github.com/doomemacs/themes/blob/3152c60bb55365ebd3b042a40aa68c9b756667f7/themes/doom-tomorrow-night-theme.el
# Turns out regular0 and bright0 are used for deselected text which messes with
# the nchat text, so they are brighter than normal

[colors]
background= 1d1f21
foreground= c5c8c6

# The regular colors are mapped from the Emacs theme's base colors
regular0= 5c5e5e  # Changed from 0d0d0d to a much brighter gray
regular1= cc6666
regular2= b5bd68
regular3= f0c674
regular4= 81a2be
regular5= b294bb
regular6= 8abeb7
regular7= c5c8c6

# The bright colors are mapped to their brighter counterparts or the next base color
bright0= 757878  # Changed from 292b2b to a brighter gray
bright1= de935f
bright2= b5bd68
bright3= f0c674
bright4= 81a2be
bright5= c9b4cf
bright6= 8abeb7
bright7= ffffff

# Highlight colors
selection-foreground= 1d1f21
selection-background= 3f4040

# Cursor color
cursor= 002732 8d9fa1
