# User Variables
real_name = "Rohit Goswami"
git_email = "rog32@hi.is"

# SSH
github_id = "github_hz"
gitlab_id = "gitlab_hz"
 
# Defaults
terminal = "termite"

##########
# Colors #
##########
background = "#292C3E"
foreground = "#EBEBEB"
text = "#FF261E"
cursor = "#FF261E"
black = "#0d0d0d"
red = "#FF301B"
green = "#A0E521"
yellow = "#FFC620"
blue = "#1BA6FA"

# TeX Vars
tex_year = "2021"
