# TOML Ref: https://github.com/toml-lang/toml
# Example: https://raw.githubusercontent.com/greshake/i3status-rust/master/examples/config.toml
# Block Doc: https://greshake.github.io/i3status-rust/i3status_rs/blocks/index.html
# Repo: https://github.com/greshake/i3status-rust

[theme]
theme = "solarized-dark"
[icons]
icons = "awesome5"

[[block]]
block = "weather"
format = "IISERM $weather $temp"
[block.service]
name = "metno" # No API key, bit off +- 1 degree
lang = "en"
coordinates = ["30.66361594277602","76.72912558319638"] # IISER-M
# coordinates = ["64.140461", "-21.961226"] # Reykjavik
# coordinates = ["26.512530794602895", "80.2330716579492"] # IITK
units = "metric"

[[block]]
block = "time"
format = "Reykjavík: %I:%M %p"
timezone = "Iceland"
interval = 60

[[block]]
block = "time"
format = "Kanpur: %I:%M %p"
timezone = "Asia/Kolkata"
interval = 60

[[block]]
block = "battery"
interval = 10
format = "$percentage $time $power|N/A"

[[block]]
block = "music"
format = "$combo.str(0,20) $prev $play $next|"

# [[block]]
# block = "weather"
# format = "$weather ($location) $temp, $wind m/s $direction"
# [block.service]
# name = "openweathermap"
# api_key = "XXX"  # Needs an API key, can be an env variable
# # # city_id = "1267995" # Kanpur
# # # city_id = "3413829" # Reykjavík
# units = "metric"
