# TOML Ref: https://github.com/toml-lang/toml
# Example: https://raw.githubusercontent.com/greshake/i3status-rust/master/examples/config.toml
# Block Doc: https://greshake.github.io/i3status-rust/i3status_rs/blocks/index.html
# Repo: https://github.com/greshake/i3status-rust

[theme]
theme = "active"
[icons]
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "load"
interval = 2
format = "$1m"

[[block]]
block = "net"
interval = 2

[[block]]
block = "custom"
command = "~/.local/bin/rg-caffeine summary-status-json"
json = true
interval = 30
watch_files = ["/home/rgoswami/.local/state"]
[[block.click]]
button = "left"
cmd = "~/.local/bin/rg-caffeine toggle"
[[block.click]]
button = "middle"
cmd = "~/.local/bin/rg-caffeine performance-toggle"
[[block.click]]
button = "right"
cmd = "~/.local/bin/rg-caffeine focus-toggle"
[[block.click]]
button = "up"
cmd = "~/.local/bin/rg-caffeine timed 2h"
[[block.click]]
button = "down"
cmd = "~/.local/bin/rg-caffeine off"

[[block]]
block = "time"
interval = 60
[block.format]
# full = " $icon $timestamp.datetime(f:'%a %R %Z') "
short = " $icon $timestamp.datetime(f:%R) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"
